In [2]:
import pandas as pd
import xlrd
df = pd.read_excel("Clinical parameters Dataset.xlsx")
df

,№,Age,IVF/ICSI cycle,"FSH, IU/L","LH, IU/L","AMH, ng/mL","Progesterone, nmol/L",Follicles obtained,LH/FSH ratio,FSHB c.-211 G>T,FSHR c.2039 A>G
0,1,35,1,7.30,2.42,1.19,8.20,10,0.331507,TT,AG
1,2,33,1,8.80,6.90,5.90,4.70,14,0.784091,GG,AG
2,3,38,1,9.40,3.70,3.04,0.95,15,0.393617,GG,AA
3,4,30,1,5.76,5.55,1.86,0.95,5,0.963542,GG,GG
4,5,34,1,6.35,8.80,2.25,0.90,4,1.385827,GT,GG
...,...,...,...,...,...,...,...,...,...,...,...
139,140,33,1,6.90,11.10,3.80,11.70,2,1.608696,GG,AG
140,141,34,2,7.91,4.21,2.94,0.40,12,0.532238,GG,AG
141,142,34,1,5.67,3.98,1.32,0.70,4,0.701940,GT,AA
142,143,34,1,8.18,11.20,10.02,1.85,20,1.369193,GG,GG
143,144,34,2,6.12,10.10,9.51,2.03,20,1.650327,GG,GG

In [4]:
# Filter the DataFrame to keep only rows where the "Type of ART" column is 0 (IVF)
df1 = df[df['IVF/ICSI cycle'] == 1]
df1

,№,Age,IVF/ICSI cycle,"FSH, IU/L","LH, IU/L","AMH, ng/mL","Progesterone, nmol/L",Follicles obtained,LH/FSH ratio,FSHB c.-211 G>T,FSHR c.2039 A>G
0,1,35,1,7.30,2.42,1.19,8.20,10,0.331507,TT,AG
1,2,33,1,8.80,6.90,5.90,4.70,14,0.784091,GG,AG
2,3,38,1,9.40,3.70,3.04,0.95,15,0.393617,GG,AA
3,4,30,1,5.76,5.55,1.86,0.95,5,0.963542,GG,GG
4,5,34,1,6.35,8.80,2.25,0.90,4,1.385827,GT,GG
...,...,...,...,...,...,...,...,...,...,...,...
137,138,33,1,6.20,6.25,4.24,1.50,7,1.008065,GT,AG
138,139,39,1,4.25,4.09,4.50,1.27,4,0.962353,GT,AG
139,140,33,1,6.90,11.10,3.80,11.70,2,1.608696,GG,AG
141,142,34,1,5.67,3.98,1.32,0.70,4,0.701940,GT,AA
142,143,34,1,8.18,11.20,10.02,1.85,20,1.369193,GG,GG

In [5]:
df1 = df.dropna()
df1

,№,Age,IVF/ICSI cycle,"FSH, IU/L","LH, IU/L","AMH, ng/mL","Progesterone, nmol/L",Follicles obtained,LH/FSH ratio,FSHB c.-211 G>T,FSHR c.2039 A>G
0,1,35,1,7.30,2.42,1.19,8.20,10,0.331507,TT,AG
1,2,33,1,8.80,6.90,5.90,4.70,14,0.784091,GG,AG
2,3,38,1,9.40,3.70,3.04,0.95,15,0.393617,GG,AA
3,4,30,1,5.76,5.55,1.86,0.95,5,0.963542,GG,GG
4,5,34,1,6.35,8.80,2.25,0.90,4,1.385827,GT,GG
...,...,...,...,...,...,...,...,...,...,...,...
139,140,33,1,6.90,11.10,3.80,11.70,2,1.608696,GG,AG
140,141,34,2,7.91,4.21,2.94,0.40,12,0.532238,GG,AG
141,142,34,1,5.67,3.98,1.32,0.70,4,0.701940,GT,AA
142,143,34,1,8.18,11.20,10.02,1.85,20,1.369193,GG,GG
143,144,34,2,6.12,10.10,9.51,2.03,20,1.650327,GG,GG

In [6]:
df1.to_excel('dataset2_for_mp.xlsx', index=False)
df1

,№,Age,IVF/ICSI cycle,"FSH, IU/L","LH, IU/L","AMH, ng/mL","Progesterone, nmol/L",Follicles obtained,LH/FSH ratio,FSHB c.-211 G>T,FSHR c.2039 A>G
0,1,35,1,7.30,2.42,1.19,8.20,10,0.331507,TT,AG
1,2,33,1,8.80,6.90,5.90,4.70,14,0.784091,GG,AG
2,3,38,1,9.40,3.70,3.04,0.95,15,0.393617,GG,AA
3,4,30,1,5.76,5.55,1.86,0.95,5,0.963542,GG,GG
4,5,34,1,6.35,8.80,2.25,0.90,4,1.385827,GT,GG
...,...,...,...,...,...,...,...,...,...,...,...
139,140,33,1,6.90,11.10,3.80,11.70,2,1.608696,GG,AG
140,141,34,2,7.91,4.21,2.94,0.40,12,0.532238,GG,AG
141,142,34,1,5.67,3.98,1.32,0.70,4,0.701940,GT,AA
142,143,34,1,8.18,11.20,10.02,1.85,20,1.369193,GG,GG
143,144,34,2,6.12,10.10,9.51,2.03,20,1.650327,GG,GG

In [7]:
descriptions = {
    '№': 'Unique identifier for each record',
    'Age': 'Age of the patient',
    'IVF/ICSI cycle': 'The cycle number of IVF/ICSI treatment',
    'FSH, IU/L': 'Follicle Stimulating Hormone level, measured in IU/L',
    'LH, IU/L': 'Luteinizing Hormone level, measured in IU/L',
    'AMH, ng/mL': 'Anti-Müllerian Hormone level, measured in ng/mL',
    'Progesterone, nmol/L': 'Progesterone level, measured in nmol/L',
    'Follicles obtained': 'Number of follicles obtained during the procedure',
    'LH/FSH ratio': 'Ratio of LH to FSH levels',
    'FSHB c.-211 G>T': 'Genetic polymorphism in the FSHB gene',
    'FSHR c.2039 A>G': 'Genetic polymorphism in the FSHR gene'
}

# Create the data dictionary DataFrame
data_dict = pd.DataFrame({
    'Column Name': df1.columns,
    'Data Type': df1.dtypes.values,
    'Description': df1.columns.map(descriptions)
})

# Save the data dictionary to a CSV file
data_dict.to_excel('data_dictionary.xlsx', index=False)

# Print the data dictionary to verify the results
print(data_dict)

             Column Name Data Type  \
0                      №     int64
1                    Age     int64
2         IVF/ICSI cycle     int64
3              FSH, IU/L   float64
4               LH, IU/L   float64
5             AMH, ng/mL   float64
6   Progesterone, nmol/L   float64
7     Follicles obtained     int64
8           LH/FSH ratio   float64
9        FSHB c.-211 G>T    object
10       FSHR c.2039 A>G    object

                                          Description
0                   Unique identifier for each record
1                                  Age of the patient
2              The cycle number of IVF/ICSI treatment
3   Follicle Stimulating Hormone level, measured i...
4         Luteinizing Hormone level, measured in IU/L
5     Anti-Müllerian Hormone level, measured in ng/mL
6              Progesterone level, measured in nmol/L
7   Number of follicles obtained during the procedure
8                           Ratio of LH to FSH levels
9               Genetic polymorphism in the FSHB gene
10              Genetic polymorphism in the FSHR gene